### ISSUE TITLE
Share result image

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Retouch#16]
User must be able to share the result without saving it. E.g. send into messenger or another app.

**Comment by mdrlzy** [comment]
I think we can do something similar

<details>
  <summary>Screenshots</summary>

![photo_2022-12-25_20-54-03](https://user-images.githubusercontent.com/85668474/209472775-8d232955-e578-4213-9bfd-c38e1d95bef2.jpg)
![photo_2022-12-25_20-54-09](https://user-images.githubusercontent.com/85668474/209472781-a92edb41-bb71-44a5-b532-161bf7151064.jpg)
</details>

**Comment by kirillt** [comment]
Implemented in #21
