### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Retouch#25]
The app displays background as white, but after saving the image it's black (if the resulting file is opened by another app). In fact, the background is transparent which results in different filling in different apps.

The color must be explicit in the code, it should be possible to change it using #6 as well. Transparent should be one of options for the color.

**Comment by kiranraoboinapally** [comment]
Is it still open to work

**Comment by kirillt** [comment]
Implemented in #41
