### ISSUE TITLE
ARK Filepicker must be used

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Retouch#28]
We have shared component https://github.com/ARK-Builders/ark-filepicker/ which, apart from plain filepicker, also adds navigation by ARK folders registered in the system. It must be convenient to use it to quickly find registered `Pictures` "root" or `Screenshots` "favorite" folder to save new image there.

Integration example can be taken from https://github.com/ARK-Builders/ARK-Navigator repo.

**Comment by ginanisque** [comment]
I am willing to work on this bounty. I have taken a look at the resources provided. I can solve the integration issues.

**Comment by kirillt** [comment]
@ginanisque please contact me in Telegram: `@kirill_taran`

**Comment by kirillt** [comment]
Implemented in #43
