### ISSUE TITLE
Handle device rotation

### ISSUE THREAD

**Issue by shubertm** [ARK-Builders/ARK-Retouch#29]
Device rotation configuration change must be handled to preserve all edits, more especially crop and rotate edits.
It should preserve the state of cropping when app is in cropping mode.
It should also preserve the state of rotation when app is in rotation mode.

**Comment by kirillt** [comment]
At the moment, no crash occurs, but the view after device rotation is incorrect.
We should handle it and re-positions elements, I guess.

**Comment by kirillt** [comment]
Solved in #50
Follow up: #64
