### ISSUE TITLE
Separate image view presentation from original image

### ISSUE THREAD

**Issue by shubertm** [ARK-Builders/ARK-Retouch#38]
Original image size should be maintained unless the user applies resize or crop (any operation that changes image dimensions)

**Comment by kirillt** [comment]
This causes images to be scaled up to user's screen.

For instance, in this screencast 1.5mb image gets upscaled to 2.8mb without any operation applied:

https://user-images.githubusercontent.com/581023/234644915-c67af143-7735-4a8f-b224-5236d51e1919.mp4

**Comment by kirillt** [comment]
This video seems related, too:

https://github.com/ARK-Builders/ARK-Retouch/assets/581023/d5499c64-9040-493a-b959-5ce70981dd97

**Comment by shubertm** [comment]
> This video seems related, too:
> 
> https://github.com/ARK-Builders/ARK-Retouch/assets/581023/d5499c64-9040-493a-b959-5ce70981dd97
> 
> 

I think, this is also why saving slows down #37

**Comment by kirillt** [comment]
Solved in #59
