### ISSUE TITLE
Limitations of Eraser mode

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Retouch#84]
When Eraser tool is selected in drawing mode users cannot:
- [x] adjust width of brush
- [x] undo last actions

It works like this because we disable any button in the toolbar while a tool is engaged. But Eraser tool is closer to a modification of Drawing mode than to dedicated tools like crop, resize, rotate etc. So we should handle it appropriately and enable some of the buttons (undo/redo, brush width).

**Comment by shubertm** [comment]
Solved in #83
